#!/bin/sh

set -eu

php_version() {
    php -r 'printf("%u.%u\n", PHP_MAJOR_VERSION, PHP_MINOR_VERSION);'
}

git_is_dirty() {
    if ! git diff-index --exit-code --ignore-submodules HEAD >/dev/null; then
        return 0
    fi

    return 1
}

modify_composerjson() {
    jq "$1" < composer.json > .composer.json.tmp
    mv .composer.json.tmp composer.json
}

main() {
    PREFERENCE="$1"; shift # highest/lowest

    WITH_PHP="${WITH_PHP:-$(php_version)}" # 5.6/7.2/etc

    COMPOSER_ARGS="--no-progress --prefer-dist"

    if git_is_dirty; then
        echo "Working tree is dirty, aborting" >&2
        return 1
    fi

    echo "Using PHP ${WITH_PHP}" >&2

    if [ "$PREFERENCE" = "lowest" ];
    then
        COMPOSER_ARGS="${COMPOSER_ARGS} --prefer-lowest --prefer-stable"
    fi

    composer update $COMPOSER_ARGS

    # Undo modifications to composer.json
    git checkout -- composer.json
}

main "$@"
